_target_: src.dataset.dataset_llff.DatasetLLFFCfg

defaults:
  - view_sampler: bounded

name: cozyroom
roots: [datasets/cozyroom]
rf_subdir: rf/rf_0
images_subdir: images
poses_file: poses_bounds.npy
hold_k: 8

# 이미지 크기 설정
image_shape: [180, 320]

# 카메라 및 렌더링 설정
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

# 전처리/필터/스케일 정규화
max_fov: 100.0
make_baseline_1: true
baseline_epsilon: 1e-3
baseline_scale_bounds: true

# 깊이 범위 설정
near: -1      # -1이면 내부에서 0.1로 치환
far: -1       # -1이면 내부에서 1000.0으로 치환

# 데이터 처리 설정
skip_bad_shape: true
augment: false
shuffle_val: true
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1