defaults:
  - view_sampler: cozyroom_eval

name: cozyroom
roots: [datasets/cozyroom_processed]
make_baseline_1: true
augment: true

image_shape: [400, 600]
skip_bad_shape: true
# test_times_per_scene: 29

# image_shape: [384, 576]
# skip_bad_shape: false
test_times_per_scene: 1

background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

test_len: -1
test_chunk_interval: 1
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true


